name: EternalLight
main: me.masstrix.eternallight.EternalLight
description: "Eternal Light makes it easy to see where mobs can spawn."
version: 1.7.1
author: Masstrix
api-version: 1.14

commands:
  eternallight:
    aliases:
      - el
    description: "Base command for Eternal Light."
    permission: "eternallight.admin"
  lightlevels:
    aliases:
      - ll
    description: "Light level options."