name: EternalLight
main: me.masstrix.eternallight.EternalLight
description: "${project.description}"
version: ${project.version}
author: Masstrix
api-version: ${target.version}

commands:
  eternallight:
    aliases:
      - el
    description: "Base command for Eternal Light."
    permission: "eternallight.admin"
  lightlevels:
    aliases:
      - ll
    description: "Light level options."