name: EternalLight
main: me.masstrix.eternallight.EternalLight
description: "${project.description}"
version: ${project.version}
author: Masstrix
api-version: 1.14

commands:
  eternallight:
    aliases:
      - el
    description: "Base command for Eternal Light."
    permission: "eternallight.admin"
  lightlevels:
    aliases:
      - ll
    description: "Light level options."
    
permissions: 
  eternalight.use:
    default: op
  eternallight.admin:
    default: op
  eternallight.mode:
    default: op
  eternallight.target:
    default: op
  eternallight.*:
    default: op
    